---

include:
  - "${COMPOSE_DIR}/adguard/docker-compose.yaml"
  - "${COMPOSE_DIR}/authelia/docker-compose.yaml"
  - "${COMPOSE_DIR}/draw.io/docker-compose.yaml"
  - "${COMPOSE_DIR}/excalidraw/docker-compose.yaml"
  - "${COMPOSE_DIR}/glances/docker-compose.yaml"
  - "${COMPOSE_DIR}/homer/docker-compose.yaml"
  - "${COMPOSE_DIR}/jackett/docker-compose.yaml"
  - "${COMPOSE_DIR}/jellyfin/docker-compose.yaml"
  - "${COMPOSE_DIR}/nginx-pm/docker-compose.yaml"
  - "${COMPOSE_DIR}/portainer/docker-compose.yaml"
  - "${COMPOSE_DIR}/pdf/docker-compose.yaml"
