---

include:
  - /tb-vol/hosting/services/authelia/docker-compose.yaml
  - /tb-vol/hosting/services/nginx-pm/docker-compose.yaml
  - /tb-vol/hosting/services/code/docker-compose.yaml
  - /tb-vol/hosting/services/draw.io/docker-compose.yaml
  - /tb-vol/hosting/services/excalidraw/docker-compose.yaml
  - /tb-vol/hosting/services/homer/docker-compose.yaml
  - /tb-vol/hosting/services/s-pdf/docker-compose.yaml
  - /tb-vol/hosting/services/jellyfin/docker-compose.yaml
  - /tb-vol/hosting/services/portainer/docker-compose.yaml
  - /tb-vol/hosting/services/pihole/docker-compose.yaml
  - /tb-vol/hosting/services/babybuddy/docker-compose.yaml
  - /tb-vol/hosting/services/glances/docker-compose.yaml


 





